// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plhghqiynimknvjrxjaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsaGdocWl5bmlta252anJ4amFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2Njg0ODksImV4cCI6MjA3MjI0NDQ4OX0.ct4Q5vn1VZaaI4pTbcq12086IDW1EWinHt_HVuJVQSs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});